### ISSUE TITLE
Clicking on labels to collapse/expand groups

### ISSUE THREAD

**Issue by Istador** [Istador/pine-interactive-map#2]
See https://github.com/stefanocudini/leaflet-panel-layers/issues/51

Options:
- <strike>Waiting for the issue to be resolved</strike>
- Fork the project and implement the change by myself (and create a pull request)

**Comment by Istador** [comment]
This issue is fixed now with commit 8b2c65adbc1d9311eecb21cf6f24926334d77b6b, but I'll keep it open until my [pull request](https://github.com/stefanocudini/leaflet-panel-layers/pull/52) is merged.

**Comment by Istador** [comment]
I forked the project, added two new features, and am using it now with commit 206f5656c5ca2d569ee63e9030d42e2b351551cc.

**Comment by stefanocudini** [comment]
merged and published v 1.2.6
