### ISSUE TITLE
When I start a new game, how do I reset this map?

### ISSUE THREAD

**Issue by MaxHeadroom68** [Istador/pine-interactive-map#37]
I could make a new Chrome user profile or something, but surely there's an obvious way to reset the check boxes on this map, and I'm just missing it?

Thanks for all your effort on this, it's very helpful!

**Comment by Istador** [comment]
Hi, the map saves all user data into the browser's `localStorage`.

When on the map, you can simply press `F12`, type `localStorage.clear()` into the `Console`, press return, and then reload the page (`F5`).

Alternatively: when on the map press `F12`, click on `Application`, expand `Local Storage`, right click on `https://pine.blackpinguin.de`, click on `Clear`, and then reload the page (`F5`).
