### ISSUE TITLE
Google docs spreadsheet is publicly writable

### ISSUE THREAD

**Issue by Istador** [Istador/pine-interactive-map#4]
Any malicious person (or bot) that knows the URL to the spreadsheet can modify it or delete entries in it.

Currently I do backups of the spreadsheet from time to time to not lose data already inserted.

To not publish the URL of the spreadsheet, the URL of the interactive map is currently not public and this repository doesn't contain the real `.env` file.

---

In the future either the spreadsheet needs to be protected in some way, or this project needs another data source.

Ways to protect the sheet could be:
- Allow only specific persons to edit it.
  - Contra: discourages collaboration.
- Allow only specific persons to edit the main sheet and offer additional sheets to contribute new data or corrections.
  - Contra: corrections are separated from the actual items, harder to insert and need to be merged to the main sheet.

Other data sources could be:
- Website with a database and forms to edit and add new data, administration area for verification.
  - Contra: too much effort to build.
  - Easy to use CMS?
- Hard-coded JSON file(s) on Github with Pull Requests.
  - Pro: easy to integrate into the JavaScript application.
  - Pro: easy to integrate into this repository (extra branch).
  - Pro: transparent change history and authorship.
  - Pro: Github CDN
  - Contra: requires Gitlhub account to contribute.
  - Contra: too complicated for the average contributor to manipulate JSON and learn Git nomenclature?
- Wiki with page protection.
  - Pro: URLs that can be linked to within popups.
  - Contra: Where to host?
    - self hosted? => slow.
    - Wikia aka. fandom.com? Needs to be created anyway by somebody. So, why not now by me?
    - [Edit:] https://pine.gamepedia.com/

Investigate:
- How do other game maps host their mapping data?

**Comment by thymaro** [comment]
As the owner of the spreadsheet, can't I roll back malicious changes in g-docs? I had the same concern when I saw how the data was growing, but I wouldn't change anything right now, as long as there are no attacks on the spreadsheet. When the game goes public and the map is widely used, we'll have to move the data to some more controlled hosting method (with new lines being suggested instead of openly edited like now).

**Comment by Istador** [comment]
The data source is now inside the official [Pine Wiki](https://pine.gamepedia.com/) (the [official website](https://pine-game.com/) is advertising it as the official wiki), and the map is using it from now on (the google spreadsheet isn't used anymore).

Because the website where the interactive map is hosted on doesn't contain the URL to the publicly writable spreadsheet anymore, its URL is published now: https://pine.blackpinguin.de/

---

The new [data source](https://pine.gamepedia.com/Interactive_Map) is protected against edits from unregistered users. To protect it, I have claimed the unmaintained wiki and am its administrator now.

To contribute it is necessary to register an user account for the wiki which gets [autoconfirmed](https://en.wikipedia.org/wiki/Wikipedia:User_access_levels#Autoconfirmed_and_confirmed_users).

Unfortunately the wiki is hosted via Gamepedia which requires a Twitch account.

---

It already supports links and formatting (bold and italic) inside the table cells. This is useful, to link to specific wiki pages from within the map's popups (which is already used).

The content pages in the wiki need to be created and maintained though. I already created some based on the current Beta version (more to come soon).

Support for images (issue #12) should be easy to implement now, as the images can easily be uploaded to the wiki.

I'll work on issue #18 soon, to allow the wiki to link to specific markers and coordinates on the map.
